<template>
  <div id="app" class="WhitePage">
    <MainPage :HideFooter="true">
      <div class="Text">
        <pre>
          TERMS OF USE

          <a href="https://www.HeyPorn.COM">HeyPorn.COM</a> PRESENTS PICTURES OF AND AUDIOVISUAL WORKS DEPICTING NUDE FEMALES AND MALES ENGAGING IN SEXUAL ACTIVITIES. YOU UNDERSTAND THAT BY USING THIS SERVICE, AND BY MERELY ACCESSING THIS WEBSITE, YOU MAY BE EXPOSED TO CONTENT THAT IS OFFENSIVE, INDECENT, OR OBJECTIONABLE. THE MATERIAL ON THIS WEBSITE/SERVER IS ADULT ORIENTED AND/OR SEXUALLY EXPLICIT AND IS RELATED TO MATERIAL OF AN ADULT NATURE. THE FOLLOWING DESCRIBES THE TERMS UNDER WHICH HEY INDUSTRY LIMITED, OPERATOR OF <a href="https://www.HeyPorn.COM">HeyPorn.COM</a> OFFERS YOU ACCESS TO ITS WEBSITE AND SERVICES. ACCESS IS MADE AVAILABLE ONLY TO THOSE WHO ACCEPT THE TERMS OF THE FOLLOWING AGREEMENT:

          YOU MUST BE AT LEAST 18 YEARS OLD TO ACCESS AND USE HeyPorn.COM’S WEBSITE AND SERVICES.

          Subscription, End User License Agreement & Terms of Service

          This Subscription, End User License Agreement & Terms of Service (the “Subscription Agreement”) is a binding contract between you, an individual user (“you”) and Hey Industry Limited., an California corporation with offices at 4590 MacArthur Blvd. Suite 500-343 Newport Beach, CA 92660 USA (“HILTD”), governing your use of the Website and Service (defined in Section 2A, below).
          THESE TERMS OF SERVICE APPLY TO ALL USERS, INCLUDING USERS WHO ARE ALSO CONTRIBUTORS OF CONTENT, OF ANY OF THE WEBSITES, WEB PAGES, INTERACTIVE FEATURES, EMBEDDABLE PLAYER, UPLOADER AND OTHER APPLICATIONS, WIDGETS, BLOGS, SOCIAL NETWORKS, SOCIAL NETWORK "TABS", OR OTHER ONLINE OR WIRELESS OFFERINGS THAT POST A LINK TO THESE TERMS OF SERVICE, WHETHER ACCESSED VIA COMPUTER, MOBILE DEVICE, OR OTHER TECHNOLOGY, MANNER, OR MEANS.

          BY ACCESSING THE WEBSITE AND/OR USING THE SERVICE, YOU AGREE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THIS SUBSCRIPTION AGREEMENT. IF YOU DO NOT AGREE, YOU MAY NOT ACCESS OR USE THE SERVICE. CONTACT <a href="mailto:CONTACTUS@HEYPORN.COM">CONTACTUS@HEYPORN.COM</a>. IF YOU WANT HILTD TO SEND YOU A COPY OF THIS SUBSCRIPTION AGREEMENT AND HILTD’S PRIVACY POLICY.

          Material Terms:

          As provided in greater detail in this Subscription Agreement (and without limiting the express language of this Subscription Agreement), you acknowledge the following: the Service is licensed, not sold to you, and that you may use the Service only as set forth in this Subscription Agreement;

          The use of the Service may be subject to separate third-party terms of service and fees, including, without limitation, your mobile network operator’s terms of service and fees, including fees charged for data usage and overage, which are your sole responsibility; the Website and Service presents pictures of nude males and females and audiovisual works depicting nude females and males engaging in sexual activities. You understand that by using this Service, and by merely accessing this Website, you may be exposed to content that is offensive, indecent, or objectionable.

          You agree not to reproduce, duplicate, copy, sell, distribute, rent, resell or exploit any portion of the Website, Service, use of the Service, or access to the Service; you consent to the collection, use, and disclosure of your personally identifiable information in accordance with HILTD’s Privacy Policy;

          The Website and Service is provided “as is” without warranties of any kind and HILTD’s liability to you is limited;

          Subscription to the Service is on an auto-renewal program which means the Subscription Fee will be charged either monthly, quarterly or annually and will continue until the Subscriber cancels pursuant to Section 5, below;

          The Subscriber may cancel his/her Subscription at any time subject to Section 5, below; some disputes arising hereunder will be resolved by binding arbitration. By accepting this Subscription Agreement, as provided in greater detail in Section 20 of this Subscription Agreement, you and HILTD are each waiving the right to a trial by jury or to participate in a class action;

          1. SCOPE OF LICENSE. The Service is licensed, not sold, to you for use only under the terms of this Subscription Agreement. HILTD reserves all rights not expressly granted to you. Subject to your complete and ongoing compliance with the terms and conditions of this Subscription Agreement, HILTD hereby grants you a personal, limited, revocable, non-transferable license to use the Service on a single compatible device that you own or control, solely for your own private, personal, non-commercial use.

          You may not make the Service available over a network where it could be used by multiple devices at the same time. You may not rent, lease, lend, redistribute or sublicense the Service.

          You may not attempt to derive the source code of, modify, or create derivative works of the Service, any updates, or any part thereof (except as and only to the extent any foregoing restriction is prohibited by applicable law). If you breach these license restrictions or the restrictions set forth in Section 10, or otherwise exceed the scope of the licenses granted herein, then you may be subject to prosecution and damages, as well as liability for infringement of intellectual property rights. The terms of this Subscription Agreement will govern any updates provided to you by HILTD that replace and/or supplement the original Service, unless such upgrade is accompanied by a separate license or revised Subscription Agreement, in which case the terms of that license or revised Subscription Agreement will govern.

          2. GENERAL. A. Description of Services. The “Service(s)” means, collectively, HILTD’s: (a) audiovisual service offering access to a selection of audiovisual works and other content (the “Service”), whether available through our website located at <a href="https://heyporn.com">https://heyporn.com</a> (the “Website”) or through any software applications made available for mobile devices (“Service Applications”);

          (b) all software, external players, buttons and widgets, data, text, images, sounds, video, graphics and photos made available by HILTD through any of the foregoing; and

          (c) any updates, new versions, new releases, additional features and functionality that HILTD may offer in connection with the foregoing ((a)-c) collectively, the “Content”). B. Consideration. You understand and agree that this Subscription Agreement is entered into in consideration of your payment of the Subscription Fee (defined below) for your access to and use of the Service pursuant to this Subscription Agreement (the “Subscription”), and for other good and valuable consideration, the receipt and sufficiency of which are hereby acknowledged. Any end user who accesses and uses the public-facing portions of the Service will be referred to herein as a “Visitor,” and any end user who registers for a Subscription will be referred to herein as a “Subscriber”. The term “Users” refers to Visitors and Subscribers collectively.

          C. Changes to the Service. HILTD may at its sole discretion and from time to time change, add or remove features and functionality of the Service without any notice to you. HILTD reserves the right to discontinue some or all of the features of the Service at any time at its sole discretion. You acknowledge and agree that HILTD will not be liable to you or to any third party for any modification, suspension or discontinuance of the Service. If you are dissatisfied with any changes to the Service, then your sole option is to discontinue or terminate your use of the Service as described herein. Notwithstanding anything in this Subscription Agreement to the contrary, if you have signed up for a Subscription and HILTD cancels your Subscription without cause, then HILTD will offer you the pro-rated, unearned portion of any amounts that you have prepaid to HILTD for such Subscription.

          D. Changes to this Subscription Agreement. The Service is owned and operated by HILTD, and HILTD reserves the right to revise this Subscription Agreement in an immaterial manner its sole discretion at any time and without prior notice to you other than by posting the revised Subscription Agreement on the Service. Unless otherwise stated in the Service, revisions to this Subscription Agreement are effective upon posting and your continued use of the Service after a revised version of this Subscription Agreement has been posted by HILTD to the Service constitutes your binding acceptance of such revised Subscription Agreement. This Subscription Agreement will be identified as of the most recent date of revision.

          Notwithstanding the preceding sentences of this Section 2D, no revisions to this Subscription Agreement will apply to any dispute between you and HILTD that arose prior to the effective date of such revision.

          3. THE WEBSITE AND SERVICE. A. Privacy Policy. Your use of the Website and Service is subject to the Privacy Policy, which is hereby incorporated by reference into this Subscription Agreement. By using the Website and/or Service, you agree that you have read, understood, and agree to the data collection, use, and disclosure provisions set forth in the Privacy Policy.

          B. Mobile Services. The Service includes certain services that are available via a mobile device, including:

          (a) the ability to browse the Service from a mobile device; and

          (b) the ability to access certain features of the Service through Service Applications downloaded and installed on a mobile device (collectively, the “Mobile Services”). To the extent that you access the Service through a mobile device, your wireless service carrier’s standard charges, data rates and other fees may apply, and you acknowledge that you are solely responsible for all such fees and charges. In addition, your carrier may restrict downloading, installing, or using certain Mobile Services, and not all Mobile Services may work with all carriers or devices.

          C. Service Security. You are prohibited from violating, or attempting to violate, the security of the Service. Any such violations may result in criminal and/or civil penalties against you, as well as the termination of your privilege to use the Service, at HILTD’s sole discretion. HILTD reserves the right to investigate any alleged or suspected violations and, if a criminal violation is suspected, refer such suspected violation to the appropriate law enforcement agencies and cooperate fully with such investigations, including, but not limited to, the disclosure of any or all of your activities on or related to the Service. You agree to promptly notify HILTD if you learn or reasonably suspect that any security breach related to the Service has occurred.

          4. REGISTRATION AND ELIGIBILITY. A. Account. You may access the public-facing portions of the Service as a Visitor. To access certain additional features and functionality of the Service, you must register an account with HILTD. All information provided to HILTD during registration will be held and used in accordance with HILTD’s Privacy Policy. You are responsible for maintaining the confidentiality of your log- in credentials in order to use the Service and are fully responsible for all activities that occur through the use of your credentials. You agree to notify HILTD immediately of any unauthorized use of your log-in credentials or any other breach of security with respect to your account. HILTD will not be liable for any loss or damage arising from unauthorized use of your credentials prior to you notifying HILTD of such unauthorized use or loss of your credentials.

          B. Accuracy of Information. You agree to provide true, accurate, current, and complete information about yourself as requested in any registration forms and to update the information about yourself promptly, and as necessary, to keep it current and accurate.

          C. Subscriptions. You may sign up for either a monthly, bi-monthly, quarterly or annual paid Subscription to the Service at any time. You will be required to register an account with HILTD and you will gain full access to Content made available through the Service as long as you maintain an active Subscription. Please refer to Section 5 below for additional information about Subscription plans, payment, and cancellation.

          D. Children. The Website, Service, and Mobile Service is not intended for children and you agree that you are over the age of 18 years and that you will not use, display, show or otherwise use the Service in the presence of children. The Service is not intended for anyone under the age of 18. IF YOU ARE UNDER 18 YEARS OF AGE, THEN YOU MUST NOT USE OR ACCESS THE SERVICE AT ANY TIME OR IN ANY MANNER. You must be at least the age of majority in your jurisdiction to use the Service. By using the Service, you affirm that you are (a) either above the age of majority in your jurisdiction; and (b) are fully able and competent to enter into and abide by the terms, conditions, obligations, affirmations, representations, and warranties set forth in this Subscription Agreement.

          5. FEES AND PAYMENT TERMS. A. SUBSCRIPTION FEES. THE TERMS BELOW APPLY TO SUBSCRIPTIONS MADE AVAILABLE THROUGH THE SERVICE (“PAYMENT TERMS”). IF YOU ARE A SUBSCRIBER, THEN YOU AGREE TO PAY THE SUBSCRIPTION FEE (DEFINED IN SECTION 5B3 BELOW) ON A TIMELY BASIS.

          B. PAYMENT TERMS. 1) BY USING THE SERVICE, OR BY REGISTERING FOR AN ACCOUNT, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE PAYMENT TERMS, AS MAY BE AMENDED BY HILTD FROM TIME TO TIME AT OUR DISCRETION.

          2) WE ACCEPT VARIOUS FORMS OF PAYMENT, AS SET FORTH ON THE WEBSITE FROM TIME TO TIME. WE DO NOT ACCEPT CASH OR CHECKS. PAYMENTS ARE PROCESSED BY OUR THIRD-PARTY PAYMENT PROCESSOR(S).

          3) THE DAY WHEN YOU REGISTER FOR AND PURCHASE OR ACTIVATE YOUR SUBSCRIPTION (“ACTIVATION DATE”) IS THE FIRST DAY OF YOUR BILLING CYCLE. BY PROVIDING YOUR PAYMENT METHOD AND OBTAINING A SUBSCRIPTION TO THE SERVICE, YOU AUTHORIZE OUR PAYMENT PROCESSOR TO CHARGE TO YOUR DESIGNATED PAYMENT METHOD THE APPLICABLE MONTHLY OR ANNUALLY RECURRING SUBSCRIPTION FEES, AND ANY APPLICABLE SALES, TELECOMMUNICATION, EXCISE, VALUED-ADDED OR SIMILAR TAXES (“SUBSCRIPTION FEE”). THE SUBSCRIPTION FEE IS EXCLUSIVE OF ANY APPLICABLE FEDERAL, STATE, PROVINCIAL, VAT OR MUNICIPAL TAXES OR DUTIES.

          4) UNLESS YOU NOTIFY US OF YOUR DECISION TO TERMINATE YOUR SUBSCRIPTION, YOUR SUBSCRIPTION WILL AUTOMATICALLY RENEW AT THE END OF EACH SUBSCRIPTION TERM AT THE THEN- CURRENT SUBSCRIPTION FEE. A RENEWED SUBSCRIPTION WILL HAVE THE SAME TERM AS THE IMMEDIATELY PRECEDING SUBSCRIPTION. AT THE TIME OF RENEWAL, YOUR PAYMENT METHOD WILL BE CHARGED THE SUBSCRIPTION FEE.

          5) YOUR PAYMENT METHOD WILL BE CHARGED FOR THE RENEWAL TERM OF YOUR SUBSCRIPTION ON YOUR BILLING DATE (“BILLING DATE”), BASED ON THE TYPE OF SUBSCRIPTION (E.G., ON A PARTICULAR DATE EACH MONTH FOR A MONTHLY SUBSCRIPTION). IF, HOWEVER, THE ACTIVATION DATE OF YOUR SUBSCRIPTION IS ON THE 29TH, 30TH OR 31ST DAY OF A MONTH, AND YOUR BILLING DATE DOES NOT EXIST IN A PARTICULAR MONTH BECAUSE THERE ARE FEWER THAN THIRTY-ONE (31) DAYS IN THE MONTH PAYMENT IS DUE, THEN YOUR BILLING DATE FOR THAT PARTICULAR RENEWAL WILL BE ON THE LAST DAY OF THE MONTH IN WHICH YOUR BILLING DATE WOULD OTHERWISE BE. THE SUBSCRIPTION FEE IS PAYABLE IN U.S. DOLLARS ONLY.

          6) IF YOU FAIL TO PAY THE APPLICABLE SUBSCRIPTION FEE WHEN DUE, THEN YOUR ACCOUNT MAY BE DOWNGRADED, SUSPENDED OR CANCELLED, AT HILTD’S SOLE DISCRETION. IF YOUR ACCOUNT IS SUSPENDED, THEN HILTD MAY, BUT IS NOT OBLIGATED TO, MAINTAIN YOUR ACCOUNT AND/OR RELATED CONTENT AND INFORMATION, IN ORDER TO ALLOW YOU TO PAY THE PAST-DUE CHARGES AND RESTORE YOUR ACCOUNT. IF THE CHARGES ARE NOT PAID, THEN YOUR ACCOUNT MAY BE CANCELLED.

          7) YOU MAY CANCEL YOUR SUBSCRIPTION TO THE SERVICE AT ANY TIME FOR ANY OR NO REASON. IF YOU CANCEL YOUR SUBSCRIPTION, THEN YOU WILL HAVE ACCESS TO THE FULL SERVICE UNTIL THE DATE THAT WOULD HAVE BEEN YOUR NEXT BILLING DATE. TO CANCEL AN ONGOING SUBSCRIPTION, PLEASE CONTACT US AT <a href="mailto:CONTACTUS@HEYPORN.COM">CONTACTUS@HEYPORN.COM</a>. ONCE YOU HAVE CANCELLED YOUR SUBSCRIPTION, WE WILL STOP BILLING YOUR APPLICABLE PAYMENT METHOD. IF YOU RESIDE IN A COUNTRY THAT IS PARTY OF THE EUROPEAN UNION AND PURCHASED A SUBSCRIPTION, YOU MAY CANCEL YOUR SUBSCRIPTION AND RECEIVE A FULL REFUND OF YOUR SUBSCRIPTION FEE WITHIN 14 DAYS OF THE ACTIVATION DATE, BUT ONLY IF YOU HAVE NOT LOGGED IN OR OTHERWISE ACTIVATED YOUR SUBSCRIPTION.

          8) WE RESERVE THE RIGHT TO CHANGE HILTD’S SUBSCRIPTION FEE OR PRICES AT ANY TIME IN OUR SOLE DISCRETION. IF HILTD DOES CHANGE the SUBSCRIPTION FEE OR PRICES, THEN WE WILL PROVIDE NOTICE OF THE CHANGE IN AN EMAIL TO YOU AT LEAST THIRTY (30) DAYS BEFORE THE CHANGE IS TO TAKE EFFECT. YOUR CONTINUED USE OF THE SERVICES AFTER THE PRICE CHANGE BECOMES EFFECTIVE CONSTITUTES YOUR AGREEMENT TO PAY THE CHANGED AMOUNT.

          6. ADVERTISEMENTS. A. Third Party Advertisements. HILTD may display advertisements for the goods and services of third parties or other promotional materials on the Service. Your dealings with, or participation in, promotions of any third-party advertisers on the Service, are solely between you and such third party, and your participation is subject to any terms and conditions associated with that advertisement or promotion. HILTD does not endorse or represent such third parties, and by using the Service, you agree that HILTD is not responsible or liable for any loss or damage of any sort incurred as a result of any such dealings or the presence of such third parties on the Service.

          B. Third Party Sites. The Service may also include links to third party websites or third-party services that are not owned or operated by HILTD (collectively, “Third-Party Sites”). HILTD does not endorse or represent such third parties and HILTD is not responsible for the availability of these Third-Party Sites, or any products, services and/or content contained therein. You agree that we are not responsible or liable, directly or indirectly, for any loss or damage of any sort incurred as a result of your use of or reliance on any Third-Party Sites. Certain functionalities of the Service may also require that you agree to additional terms and conditions of Third Party Sites. You agree that you are solely responsible for your acceptance of and compliance with such terms and conditions whenever you use or access such Third-Party Sites.

          7. SPECIAL NOTICE FOR INTERNATIONAL USE; EXPORT CONTROLS. Software available in connection with the Service, the Content, and the transmission of applicable data, if any, is subject to United States export controls. No software may be downloaded from the Service or otherwise exported or re- exported in violation of U.S. export laws. You use the Service and related software at your sole risk. Recognizing the global nature of the Internet, you agree to comply with all local rules and laws regarding your use of the Service, including as it concerns online conduct and acceptable content. HILTD makes no representation that the Service is appropriate or available for use in any particular location.

          8. CONTENT YOU SUBMIT; LICENSE GRANTS FROM YOU. A. User Content. This Section governs any material that you post, send or transmit (collectively, “Post”) through the Service, including, by way of example and not limitation, videos, photographs, graphics, images, text, musical works, sound recordings, digital phonorecord deliveries, and any other content, materials or works subject to protection under the laws of the United States or any other jurisdiction, including, but not limited to, patent, trademark, trade secret, and copyright laws (collectively, “User Content”). You are solely responsible for securing the rights to any and all User Content you Post to or through the Service.

          B. License Grants to HILTD and other Users. (1) LICENSE GRANT. BY POSTING USER CONTENT TO OR THROUGH THE SERVICE, YOU HEREBY GRANT TO HILTD (AND HILTD’S ASSIGNEES, DESIGNEES, SUCCESSORS, LICENSEES, AND SUB-LICENSEES) AN UNRESTRICTED, PERPETUAL, ASSIGNABLE, SUBLICENSABLE, REVOCABLE, ROYALTY-FREE, FULLY PAID UP LICENSE THROUGHOUT THE WORLD TO REPRODUCE, MODIFY, DISTRIBUTE, DISPLAY, PUBLISH, TRANSMIT, COMMUNICATE TO THE PUBLIC, MAKE AVAILABLE, BROADCAST, CREATE DERIVATIVE WORKS FROM, PUBLICLY PERFORM (INCLUDING ON A THROUGH-TO-THE AUDIENCE BASIS), DELIVER AND PUBLICLY PERFORM DIGITAL PHONORECORDS, AND OTHERWISE USE AND EXPLOIT (COLLECTIVELY, “USE”) ALL USER CONTENT YOU POST TO OR THROUGH THE SERVICE, THROUGH ANY MEDIA AND FORMATS NOW KNOWN OR HEREAFTER DEVELOPED, IN CONNECTION WITH THE SERVICE, INCLUDING, WITHOUT LIMITATION, (A) IN CONNECTION WITH OR ON ANY THIRD PARTY SITES AND PLATFORMS WHERE THE SERVICE IS SYNDICATED; AND (B) TO ADVERTISE, MARKET AND PROMOTE THE AVAILABILITY OF USER CONTENT AND THE SERVICE. BY WAY OF EXAMPLE ONLY AND WITHOUT LIMITING THE FOREGOING LICENSE, HILTD WILL HAVE THE RIGHT TO INSERT, PLACE OR INCLUDE ALL TYPES OF ADVERTISEMENTS WITHIN OR AROUND USER CONTENT, INCLUDING, WITHOUT LIMITATION, RUNNING OR STREAMING PRE-ROLLS, MID-ROLLS, POST-ROLLS, DISPLAY ADS, OVERLAYS, BANNERS, CAMPAIGN AND COMPANION ADS AND ANY OTHER TYPE OF ADVERTISING, WHETHER AUDIO, VISUAL, OR AUDIOVISUAL UNITS IN CONNECTION WITH USER CONTENT. NOTWITHSTANDING THE PRECEDING SENTENCES OF THIS SECTION, IF YOU REMOVE ANY OF YOUR USER CONTENT USING FUNCTIONALITIES AVAILABLE THROUGH THE SERVICE, THEN YOU AGREE TO, AND HEREBY DO GRANT, HILTD A PERPETUAL AND IRREVOCABLE LICENSE TO USE ANY BACKUP COPIES OF YOUR USER CONTENT THAT HILTD MADE PRIOR TO YOUR REMOVAL OF YOUR USER CONTENT AND IN THE ORDINARY COURSE OF BUSINESS.

          (2) License for Name, Image, Voice, and Likeness. You further hereby grant HILTD a royalty-free license to Use your name, image, voice, trademarks, logos, monikers, and likeness (and that of any person identifiable in any User Content you posted to or through the Service) made available by or on your behalf through the Service in conjunction with your User Content. The foregoing license in the immediately preceding sentence will survive the termination of your account with respect to any of your User Content Posted to the Service prior to such termination.

          C. Limited Waiver of Rights. You waive any and all rights of privacy, rights of publicity, or any other rights of a similar nature in connection with your User Content, or any portion thereof. To the extent any moral rights are not transferable or assignable, you hereby waive and agree never to assert any and all moral rights, or to support, maintain or permit any action based on any moral rights that you may have in or with respect to any of your User Content Posted to the Service, during the term of this Subscription Agreement. You expressly release HILTD and all of HILTD’s agents, partners, subsidiaries, affiliates, licensees, successors, and assigns from any and all claims, demands, liabilities, or causes of action, whether now known or unknown, for defamation, copyright infringement, violation of moral rights, and invasion of the rights to privacy, right to publicity, or personality or any similar matter, or based upon or relating to the Use of your User Content as authorized in this Subscription Agreement.

          D. Representations and Warranties With Respect to Your User Content. Except for materials provided to you by HILTD through the Service, you represent, warrant, and covenant that (1) you either are the sole and exclusive owner of all of your User Content, or you have all rights, licenses, consents, and releases that are necessary to grant to HILTD the rights in your User Content as contemplated under this Subscription Agreement; and (2) neither your User Content nor your creation of, accessing, posting, submission or transmission of your User Content will (x) infringe, misappropriate or violate the rights of any party or entity, including a third party’s patent, copyright, trademark, trade secret, moral rights, rights of publicity, rights of privacy or other intellectual property or proprietary rights; (y) constitute or result in defamation, libel, slander, or the violation of any applicable law or regulation (including, without limitation, restrictions on obscenity, child pornography, wiretap laws or other similar restrictions on nonconsensual recording, or otherwise); or (z) require HILTD to obtain any licenses from or make any payments in any amounts to any third party throughout the world.

          E. Proof of Rights Clearance. HILTD may require you to provide sufficient evidence of having all necessary 18 U.S.C. 2257 documents and identification documents, rights, licenses, authorizations, permissions, and clearances for any of your User Content that you Post to the Service, and if you fail to provide such evidence within a reasonable period of time (as determined by HILTD in its sole discretion), then HILTD may remove some or all of your User Content from the Service and/or terminate your account, without any liability to you. You are solely responsible for keeping copies of such evidence.

          F. Monitoring. HILTD has the right, but not the obligation, to monitor the Service, and User Content, and may remove any User Content from the Service for any reason in its sole discretion at any time, without notice and without any liability to you. You acknowledge that HILTD may establish general practices and limits concerning use of the Service without notice to you, including, without limitation, the maximum period of time that User Content will be retained by the Service and the maximum storage space that will be allotted on HILTD’s servers on your behalf. You acknowledge and agree that HILTD may preserve any Content and may also disclose any Content if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (1) comply with legal process, applicable laws or government requests; (2) enforce this Subscription Agreement; (3) respond to claims that any content violates the rights of third parties; or (4) protect the rights, property, or personal safety of HILTD, its Users and the public. You understand that HILTD does not guarantee any confidentiality with respect to User Content and will have no responsibility or liability for User Content that is deleted from the Service. HILTD does not endorse any User Content submitted by any user or other licensor, or any opinion, recommendation, or advice expressed therein, and HILTD expressly disclaim any and all liability in connection with User Content. HILTD do not permit copyright infringing activities and infringement of intellectual property rights on the Service, and HILTD will remove all User Content if properly notified that such User Content infringes on another’s intellectual property rights. HILTD reserves the right to remove Content without prior notice.

          10. USE RESTRICTIONS. Your rights to use the Service and the User Content are expressly conditioned on the following:

          A. You may access the Service for your personal entertainment purposes only solely as intended through the provided functionality of the Service and as permitted under this Subscription Agreement.

          B. You may not copy, distribute, re-sell, alter, modify, create derivative works of, sell, license or in any way exploit any part of the Service or any User Content.

          C. You agree not to copy, reproduce, distribute, publish, display, perform, transmit, stream or broadcast any part of the Service or User Content without HILTD’s prior written authorization, including, by way of example and not limitation, by doing or engaging in any of the following without HILTD’s prior express written consent:

          1) altering, defacing, mutilating or otherwise bypassing any approved software through which the Service is made available; and

          2) using any trademarks, service marks, design marks, logos, photographs or other content belonging to HILTD or obtained from the Service.

          D. You agree not to bypass, circumvent, damage or otherwise interfere with any security or other features of the Service designed to control the manner in which the Service is used, harvest or mine User Content from the Service, or otherwise access or use the Service in a manner inconsistent with individual human usage.

          E. You agree not to undertake, cause, permit or authorize the modification, creation of derivative works, translation, reverse engineering, decompiling, disassembling or hacking of any aspect of the Service or User Content or any part thereof, or attempt to do any of the foregoing, except and solely to the extent permitted by this Subscription Agreement, the authorized features of the Service or User Content, or by law, or otherwise attempt to use or access any portion of the Service other than as intended by HILTD.

          F. You agree not to use, display, mirror, frame or utilize framing techniques to enclose the Service or the User Content, or any portion thereof, through any other application or website, unless and solely to the extent HILTD makes available the means for embedding any part of the Service or the User Content.

          G. You agree not to access, tamper with, or use non-public areas of the Service, HILTD’s (and its hosting company’s) computer systems and infrastructure, or the technical delivery systems of HILTD’s providers.

          H. You agree not to harass, abuse, harm or advocate or incite harassment, abuse or harm of another person or group, including HILTD employees.

          I. You agree not to provide any false personal information to HILTD.

          J. You agree not to create a false identify or impersonate another person or entity in any way.

          K. You agree not to create a new account with HILTD, without HILTD’s express written consent if HILTD has previously disabled, suspended or terminated an account of yours for any reason whatsoever.

          L. You agree not to solicit, or attempt to solicit, personal information from other Users.

          M. You agree not to restrict, discourage or inhibit any person from using the Service, disclose personal information about a third person on the Service or obtained from the Service without the consent of such person, or collect information about Users of the Service.

          N. You agree not to use the Service, without HILTD’s express written consent, for any commercial purpose, including reselling, distributing, or communicating or facilitating any commercial advertisement or solicitation.

          O. You agree not to gain unauthorized access to the Service, to other Users’ accounts, names or personally identifiable information, or to other computers or websites connected or linked to the Service.

          P. You agree not to Post, transmit or otherwise make available, including in any of your User Content, any virus, worm, spyware or any other computer code, file or program that may or is intended to disable, overburden, impair, damage or hijack the operation of any hardware, software or telecommunications equipment, or any other aspect of the Service or User Content or communications equipment and computers connected to the Service.

          Q. You agree not to Post any User Content that is or could be interpreted to be defamatory, libelous, inaccurate, unlawful, harmful, threatening, abusive, harassing, vulgar, offensive, obscene, pornographic, objectionable, or hateful, or that promotes discrimination, bigotry, racism, or hatred, as determined by HILTD in its sole discretion.

          R. You agree not to Post any User Content that does or could be claimed to infringe any third party intellectual property or other rights, including the rights of privacy, publicity and confidentiality.

          S. You agree not to interfere with or disrupt the Service, networks or servers connected to the Service or violate the regulations, policies or procedures of such networks or servers.

          T. You agree not to violate any applicable federal, state or local laws or regulations (including, without limitation, any traffic laws and rules applicable when you use the Service in a vehicle) or this Subscription Agreement through the use of the Service.

          U. You agree not to assist or permit any persons in engaging in any of the activities described above.
          V. You agree not to post any User Content containing sweepstakes, contests, or lotteries, or otherwise related to gambling.

          W. YOU AGREE AND UNDERSTAND THAT ANY AND ALL VIOLATIONS OF PARAGRAPH 10 CAN AND WILL BE MET WITH LITIGATION INSTITUTED BY HILTD AGAINST YOU AND/OR THE ACCOUNT HOLDER OF THE INTERNET SERVICE THROUGH WHICH SUCH ACTIVITY OCCURRED.

          11. SECURITY. You understand that the operation of the Service, including User Content, may be unencrypted and involve (a) transmissions over various networks; (b) changes to conform and adapt to technical requirements of connecting networks or devices; and (c) transmission to HILTD’s third party vendors and hosting partners to provide the necessary hardware, software, networking, storage, and related technology required to operate and maintain the Service and Content. HILTD will have no liability to you for any unauthorized access or use of your Subscription, or any corruption, deletion, destruction or loss of any of Content.

          12. OWNERSHIP. The Service, Content, and the media and materials contained therein, including all intellectual property rights therein, is the sole and exclusive property of HILTD and its licensors. Except for the limited license expressly granted by and to you under this Subscription Agreement, no other rights, licenses, or immunities are granted or will be deemed to be granted under this Subscription Agreement, either expressly, or by implication, estoppel or otherwise.

          13. FEEDBACK. While our own staff is continually working to develop and evaluate our own product ideas and features, we pride ourselves on paying close attention to the interests, feedback, comments, and suggestions we receive from Users. If you choose to contribute by sending HILTD or our employees any ideas for products, services, features, modifications, enhancements, content, refinements, technologies, content offerings (such as audiovisual or other types of content), promotions, strategies, or product/feature names, or any related documentation, artwork, computer code, diagrams, or other materials (collectively “Feedback”), then regardless of what your accompanying communication may say, the following terms will apply, so that future misunderstandings can be avoided. Accordingly, by sending Feedback to HILTD, you agree that:

          A. HILTD has no obligation to review, consider, or implement your Feedback, or to return to you all or part of any Feedback for any reason;

          B. Feedback is provided on a non-confidential basis, and HILTD is not under any obligation to keep any Feedback you send confidential or to refrain from using or disclosing it in any way; and

          C. You irrevocably grant HILTD and its successors and assigns perpetual and unlimited permission to Use the Feedback and derivatives thereof for any purpose and without restriction, free of charge and without attribution of any kind, including by making, using, selling, offering for sale, importing, and promoting commercial products and services that incorporate or embody Feedback, whether in whole or in part, and whether as provided or as modified. If you become aware of any security vulnerability in the Service or User Content, then please provide us Feedback using the “Send Feedback” feature within the Service or at <a href="mailto:contactus@heyporn.com">contactus@heyporn.com</a>.

          14. TERMINATION. This Subscription Agreement is effective until terminated by you or HILTD as described in this Section.

          A. Automatic Termination. Your rights under this Subscription Agreement will terminate automatically without notice from HILTD if you fail to comply with any term(s) of this Subscription Agreement (including by violating any license restriction provided herein or for failure to pay the Subscription Fee).

          B. Termination by You. You may terminate your account, this Subscription Agreement, and your right to use the Service, at any time and for any reason or no reason, by contacting HILTD Customer Support at <a href="mailto:contactus@heyporn.com">contactus@heyporn.com</a>.

          C. Termination by HILTD. Notwithstanding anything to the contrary in this Subscription Agreement, HILTD has the right to immediately disable, suspend, or terminate your account at any time for any reason or no reason, with or without notice to you. All of your User Content on the Service (if any) may be permanently deleted by HILTD at any time and for any reason in HILTD’s sole discretion, with or without notice to you. In addition, HILTD may notify authorities or take any actions it deems appropriate, without notice to you, if HILTD suspects or determines, in its own discretion, that you may have or there is a significant risk that you have: (a) failed to comply with any provision of this Subscription Agreement or any policies or rules established by HILTD through any of the foregoing; or (b) engaged in actions relating to or in the course of using the Service that may be illegal or cause liability, harm, embarrassment, harassment, abuse or disruption for you, HILTD, the Service, other Users or any other third parties.

          D. Effects of Termination. After any termination of this Subscription Agreement, you understand and acknowledge that (a) HILTD will have no further obligation to provide the Service or Content to you; and

          (b) all licenses and other rights granted to you in this Subscription Agreement will immediately cease. HILTD is not liable to you or any third party for termination of the Service or termination of your use of the Service. Upon any termination or suspension, you may no longer access any information that you have Posted to the Service or that is related to your account. Furthermore, HILTD will have no obligation to maintain any information stored in our database related to your account or to forward any information to you or any third party. You acknowledge and agree that HILTD will not be required to delete any of your User Content that may be stored on any servers or other back up media owned or controlled by or on behalf of HILTD following the termination of your account.

          15. INDEMNITY. You agree to indemnify and hold HILTD, and its officers, directors, employees, agents, successors, and assigns harmless from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected to (a) your access, use, or misuse of the Service, or User Content; (b) your User Content; or (c) your violation of this Subscription Agreement. HILTD will use reasonable efforts to notify you of any such claim, action or proceeding for which it seeks an indemnification from you upon becoming aware of it, but if HILTD is unable to communicate with you in a timely manner because of an inactive e-mail address for you, your indemnification obligation will continue notwithstanding HILTD’s inability to contact you in a timely manner. HILTD reserves the right to assume the exclusive defense and control of any matter that is subject to indemnification under this Section. In such case, you agree to cooperate with any reasonable requests to assist HILTD’s defense of such matter. You agree not to settle any matter without the prior express written consent of HILTD.

          16. NO WARRANTY. YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT USE OF THE SERVICE IS AT YOUR SOLE RISK AND THAT THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY AND EFFORT IS WITH YOU. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE, AND ANY CONTENT OR MATERIALS AVAILABLE THROUGH THE SERVICE (INCLUDING, WITHOUT LIMITATION, ANY USER CONTENT, THIRD PARTY CONTENT AND/OR USER CONTENT), ARE PROVIDED “AS IS” AND “AS AVAILABLE,” WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, AND HILTD HEREBY DISCLAIMS, ON BEHALF OF ITSELF AND ITS SUPPLIERS AND LICENSORS, ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THE SERVICE, AND ANY CONTENT OR MATERIALS AVAILABLE THROUGH THE SERVICE (INCLUDING, WITHOUT LIMITATION, ANY USER CONTENT, THIRD PARTY CONTENT AND/OR USER CONTENT), WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY, OF SATISFACTORY QUALITY, OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY, OF QUIET ENJOYMENT, TITLE, AND NON-INFRINGEMENT OF THIRD PARTY RIGHTS. HILTD DOES NOT WARRANT AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF THE SERVICE, THAT THE FUNCTIONS CONTAINED IN OR SERVICES PERFORMED OR PROVIDED BY THE SERVICE WILL MEET YOUR REQUIREMENTS, THAT THE OPERATION OF THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE OR NOT INTERFERE WITH YOUR USE OR ENJOYMENT OF ANY OTHER APPLICATIONS ON THE DEVICE ON WHICH THE SERVICE IS ACCESSED OR INSTALLED, OR THAT DEFECTS IN THE SERVICE WILL BE CORRECTED. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY HILTD OR ITS AUTHORIZED REPRESENTATIVES WILL CREATE A WARRANTY NOT EXPRESSLY PROVIDED FOR IN THIS SUBSCRIPTION AGREEMENT. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR LIMITATIONS ON APPLICABLE STATUTORY RIGHTS OF A CONSUMER, SO THE ABOVE EXCLUSION AND LIMITATIONS MAY NOT APPLY TO YOU, BUT IN SUCH A CASE THE FOREGOING WILL BE APPLIED TO THE GREATEST EXTENT ENFORCEABLE UNDER APPLICABLE LAW.

          17. LIMITATION OF LIABILITY. TO THE EXTENT NOT PROHIBITED BY LAW, IN NO EVENT WILL HILTD OR ITS SUPPLIERS OR LICENSORS BE LIABLE FOR PERSONAL INJURY, OR ANY INCIDENTAL, SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, LOSS OF DATA, BUSINESS INTERRUPTION OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OR INABILITY TO USE THE SERVICE AND ANY CONTENT OR MATERIALS AVAILABLE THROUGH THE SERVICE (INCLUDING, WITHOUT LIMITATION, ANY USER CONTENT, THIRD PARTY CONTENT AND/OR USER CONTENT), HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT OR OTHERWISE) AND EVEN IF HILTD HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OF LIABILITY FOR PERSONAL INJURY, OR OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU. IN NO EVENT WILL HILTD’S TOTAL LIABILITY TO YOU FOR ALL DAMAGES (OTHER THAN AS MAY BE REQUIRED BY APPLICABLE LAW IN CASES INVOLVING PERSONAL INJURY) EXCEED THE LESSER OF (A) THE AMOUNT YOU PAID TO HILTD IN THE PRECEDING 12 MONTHS; OR (B) ONE HUNDRED DOLLARS ($10.00). THE FOREGOING LIMITATIONS WILL APPLY EVEN IF THE ABOVE STATED REMEDY FAILS OF ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF OR LIMITATION OF CERTAIN TYPES OF DAMAGES OR LIABILITIES, SO THE ABOVE EXCLUSION AND LIMITATIONS MAY NOT APPLY TO YOU, BUT IN SUCH A CASE THE FOREGOING WILL BE APPLIED TO THE GREATEST EXTENT ENFORCEABLE UNDER APPLICABLE LAW.

          18. THIRD PARTY DISPUTES. HILTD IS NOT AFFILIATED WITH ANY MOBILE CARRIER, RADIO STATION OR OTHER THIRD PARTY SERVICE PROVIDER, AND ANY DISPUTE YOU HAVE WITH ANY SUCH THIRD PARTY SERVICE PROVIDER OR ANY OTHER THIRD PARTY, INCLUDING, WITHOUT LIMITATION, ANY OTHER USER OF THE SERVICE, IS DIRECTLY BETWEEN YOU AND SUCH THIRD PARTY, AND YOU IRREVOCABLY RELEASE HILTD (AND OUR OFFICERS, DIRECTORS, AGENTS, SUBSIDIARIES, JOINT VENTURES, EMPLOYEES, SUCCESSORS, AND ASSIGNS) FROM ANY AND ALL CLAIMS, DEMANDS AND DAMAGES (ACTUAL AND CONSEQUENTIAL) OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH SUCH DISPUTES.

          19. NOTICE AND PROCEDURE FOR MAKING CLAIMS OF COPYRIGHT OR OTHER INTELLECTUAL PROPERTY INFRINGEMENTS.

          A. Respect of Third Party Rights. HILTD respects the intellectual property of others and takes the protection of intellectual property very seriously, and we ask our Users to do the same. Infringing activity will not be tolerated on or through the Service.

          B. Repeat Infringer Policy. HILTD’s intellectual property policy is to (a) remove or disable access to material that HILTD believes in good faith, upon notice from an intellectual property owner or his or her agent, is infringing the intellectual property of a third party by being made available through the Service; and (b) remove any User Content you uploaded to the Service if you are a “repeat infringer” and terminate your right to use the Service. You are a “repeat infringer” if you are a User that has uploaded User Content or Feedback to or through the Service and for whom HILTD has received more than two takedown notices compliant with the provisions of 17 U.S.C. § 512 with respect to your User Content or Feedback. HILTD has discretion, however, to terminate the account of any User after receipt of a single notification of claimed infringement or upon HILTD’s own determination.

          C. Procedure for Reporting Claimed Infringement. If you believe that any content made available on or through the Service has been used or exploited in a manner that infringes an intellectual property right you own or control, then please promptly send a “Notification of Claimed Infringement” containing the following information to the Designated Agent identified below. Your Notification of Claimed Infringement may be shared by HILTD with the User alleged to have infringed a right you own or control or the general public, and you hereby consent to HILTD making such disclosure. Your communication must include substantially the following:

          1) A physical or electronic signature of a person authorized to act on behalf of the owner of the work(s) that has/have been allegedly infringed;

          2) Identification of works or materials being infringed, or, if multiple works are covered by a single notification, a representative list of such works;

          3) Identification of the specific material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit HILTD to locate the material;

          4) Information reasonably sufficient to permit HILTD to contact you, such as an address, telephone number, and, if available, an electronic mail address at which you may be contacted;

          5) A statement that you have a good faith belief that the use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and

          6) A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. You should consult with your own lawyer and/or see (a) 17 U.S.C. § 512 to confirm your obligations to provide a valid notice of claimed infringement; (b) “fair use” under 17 U.S.C. § 101 et seq.

          D. Designated Agent Contact Information. HILTD’s designated agent for receipt of Notifications of Claimed Infringement (the “Designated Agent”) can be contacted at:

          Law Offices of Michael W. Fattorosi, P.C.
          5850 Canoga Ave.
          Suite 400
          Woodland Hills, CA 91367
          <a href="mailto:legal@heyporn.com">legal@heyporn.com</a>

          E. False Notifications of Claimed Infringement or Counter Notifications. The Copyright Act provides that any person who knowingly materially misrepresents under [Section 512 of the Copyright Act (17 U.S.C. § 512)] (1) that material or activity is infringing, or (2) that material or activity was removed or disabled by mistake or misidentification, will be liable for any damages, including costs and attorneys’ fees, incurred by the alleged infringer, by any copyright owner or copyright owner’s authorized licensee, or by a service provider, who is injured by such misrepresentation, as the result of [HILTD] relying upon such misrepresentation in removing or disabling access to the material or activity claimed to be infringing, or in replacing the removed material or ceasing to disable access to it. 17 U.S.C. § 512(f). HILTD reserves the right to seek damages from any party that submits a Notification of Claimed Infringement or Counter Notification in violation of the law. THE FOLLOWING PROVISIONS OF THIS DISPUTE RESOLUTION SECTION DO NOT APPLY TO ANY CLAIM IN WHICH EITHER PARTY SEEKS RELIEF TO PROTECT SUCH PARTY’S COPYRIGHTS, TRADEMARKS, AND OR PATENTS OR OTHER RIGHTS OF AN INTELLECTUAL PROPERTY NATURE.

          20. Dispute Resolution. A. Mandatory Arbitration. Please read this carefully. It affects your rights. YOU AND HILTD AND EACH OF OUR RESPECTIVE CORPORATE PARENTS, SUBSIDIARIES, AFFILIATES, PREDECESSORS IN INTEREST, SUCCESSORS, PERMITTED ASSIGNS, AND ANY OTHER PARTIES ON WHOSE BEHALF YOU ARE ACCESSING THE SERVICE AGREE TO ARBITRATION, AS THE EXCLUSIVE FORM OF DISPUTE RESOLUTION EXCEPT AS PROVIDED FOR BELOW, FOR ALL DISPUTES AND CLAIMS ARISING OUT OF OR RELATING TO THIS SUBSCRIPTION AGREEMENT OR THE SERVICE. Arbitration is more informal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, allows for more limited discovery than in court, and is subject to very limited review by courts. Arbitrators can award the same damages and relief that a court can award. Please visit www.adr.org for more information about arbitration.

          1) Commencing Arbitration. A party who intends to seek arbitration must first send to the other, by certified mail, a written notice of intent to arbitrate (a “Notice”), or, if you do not provide a mailing address to HILTD, to you via any other method available to HILTD, including via e-mail. The Notice to HILTD should be addressed to HILTD. The Notice must (a) describe the nature and basis of the claim or dispute; and (b) set forth the specific relief sought (the “Demand”). If you and HILTD do not reach an agreement to resolve the claim within 90 days after the Notice is received, then you or HILTD may commence an arbitration proceeding as set forth below or file a claim in small claims court. THE ARBITRATION WILL BE ADMINISTERED BY THE AMERICAN ARBITRATION ASSOCIATION (“AAA”) IN ACCORDANCE WITH ITS COMMERCIAL ARBITRATION RULES AND THE SUPPLEMENTARY PROCEDURES FOR CONSUMER RELATED DISPUTES (THE “Rules”), AS MODIFIED BY THIS AGREEMENT. The Rules and AAA forms are available online at www.adr.org. If you are required to pay a filing fee to commence an arbitration against HILTD, then HILTD will promptly reimburse you for your confirmed payment of the filing fee upon HILTD’s receipt of Notice at the Arbitration Notice Address that you have commenced arbitration along with a receipt evidencing payment of the filing fee, unless your Demand is equal to or greater than $100.00 or was filed in bad faith, in which case you are solely responsible for the payment of the filing fee.

          2) Arbitration Proceeding. The arbitration will be conducted in the English language. A single independent and impartial arbitrator will be appointed pursuant to the Rules, as modified herein. You and HILTD agree to comply with the following rules, which are intended to streamline the dispute resolution process and reduce the costs and burdens on the parties: (a) the arbitration will be conducted by telephone, online and/or be solely based on written submissions, the specific manner to be chosen by the party initiating the arbitration; (b) the arbitration will not require any personal appearance by the parties or witnesses unless otherwise mutually agreed in writing by the parties; and (c) any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.

          3) No Class Actions. YOU AND HILTD AGREE THAT YOU AND HILTD MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. FURTHER, YOU AGREE THAT THE ARBITRATOR MAY NOT CONSOLIDATE PROCEEDINGS OF MORE THAN ONE PERSON’S CLAIMS, AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A REPRESENTATIVE OR CLASS PROCEEDING, AND THAT IF THIS SPECIFIC PROVISO IS FOUND TO BE UNENFORCEABLE, THEN THIS ONLY THIS SECTION A3 OF THIS MANDATORY ARBITRATION SECTION WILL BE NULL AND VOID.

          4) Decision of the Arbitrator. Barring extraordinary circumstances, the arbitrator will issue his or her decision within 180 days from the date the arbitrator is appointed. The arbitrator may extend this time limit for an additional 30 days in the interests of justice. All arbitration proceedings will be closed to the public and confidential and all records relating thereto will be permanently sealed, except as necessary to obtain court confirmation of the arbitration award. The award of the arbitrator will be in writing and will include a statement setting forth the reasons for the disposition of any claim. The arbitrator will apply the laws of the State of Arizona in conducting the arbitration. You acknowledge that these terms and your use of the Service evidences a transaction involving interstate commerce. The United StatesFederal Arbitration Act will govern the interpretation, enforcement, and proceedings pursuant to the Mandatory Arbitration clause in this Subscription Agreement.

          B. Equitable Relief. The foregoing provisions of this Dispute Resolution section do not apply to any claim in which either party seeks equitable relief to protect such party’s copyrights, trademarks, or patents. You acknowledge that, in the event of a breach of the Subscription Agreement by HILTD or any third party, the damage or harm, if any, caused to you will not entitle you to seek injunctive or other equitable relief against HILTD, and your only remedy will be for monetary damages, subject to the limitations of liability set forth in the Subscription Agreement.

          C. Claims. You and HILTD agree that, notwithstanding any other rights the party may have under law or equity, any cause of action arising out of or related to this Subscription Agreement or the Service, excluding a claim for indemnification, must commence within one year after the cause of action accrues. Otherwise, such cause of action is permanently barred.

          D. Improperly Filed Claims. All claims you bring against HILTD must be resolved in accordance with this Dispute Resolution section. All claims filed or brought contrary to this Dispute Resolution section will be considered improperly filed. Should you file a claim contrary to this Dispute Resolution section, HILTD may recover attorneys’ fees and costs up to $100,000, provided that HILTD has notified you in writing of the improperly filed claim, and you have failed to promptly withdraw the claim.

          E. Modifications. In the event that HILTD makes any future change to the Mandatory Arbitration provision (other than a change to HILTD’s Arbitration Notice Address), you may reject any such change by sending us written notice within thirty (30) days of the change to HILTD’s Arbitration Notice Address, in which case your account with HILTD and your license to use the Service will terminate immediately, and this Dispute Resolution provision, as in effect immediately prior to the amendments you reject, will survive the termination of the Subscription Agreement.

          F. Enforceability. If the entirety of this Section 20 is found to be unenforceable, then the entirety of this Section 20 will be null and void and, in such case, the parties agree that the exclusive jurisdiction and venue described in Section 21 will govern any action arising out of or related to this Subscription Agreement.

          21. Arbitration Waiver. Both parties hereby agree to waive all provisions for mediation and arbitration in regard to the issues of claims for the infringement of intellectual property. Any such claims or counter- claims shall be resolved by a court of competent jurisdiction in Los Angele County, California as outlined below. THIS PARAGRAPH SHALL SUPERSEDE AND REPLACE THE ARBTRATION PROVISION NOTED IN THIS AGREEMENT AS IT APPLIES TO CLAIMS OF INTELLECTUAL PROPERTY INFRINGEMENT AND UNFAIR BUSINESS PRACTICES.

          22. Governing Law. The laws of the State of California, excluding its conflicts of law rules, govern your use of the Service. Your use of the Service may also be subject to other local, state, national, or international laws. To the extent that any action relating to any dispute hereunder is permitted to be brought in a court of law, such action will be subject to the exclusive jurisdiction of the state and federal courts located in Los Angeles County, California, and you hereby irrevocably submit to personal jurisdiction in such courts and waive any defense of inconvenient forum. Any lawsuit filed in federal court shall be brought in the United States District Court for the Central District of California. PLEASE NOTE THAT BY AGREEING TO THIS AGREEMENT, YOU ARE WAIVING CLAIMS THAT YOU MIGHT OTHERWISE HAVE AGAINST US BASED ON THE LAWS OF OTHER JURISDICTIONS, INCLUDING YOUR OWN.

          23. Recovery of Expenses. In any proceedings between the parties arising out of or relating to claims of intellectual property infringement, the prevailing party will be entitled to recover from the other party, in addition to any other relief awarded, all expenses that the prevailing party incurs in those proceedings, including legal fees and expenses. For purposes of section, “prevailing party” means, for any proceedings, the party in whose favor an award is rendered, except that if in those proceedings the award finds in favor of one party on one or more claims or counterclaims and in favor of the other party on one or more other claims or counterclaims, neither party will be the prevailing party. If any proceedings are voluntarily dismissed or are dismissed as part of settlement of that dispute, neither party will be the prevailing party in those proceedings.

          24. Jury Trial Waiver. Each party hereby waives its right to a trial by jury in any claims arising out of or relating to the subject matter of this agreement. Either party may enforce this waiver up to and including the first day of trial.

          25. Assignment. You may not assign this Subscription Agreement or any of the rights or licenses granted hereunder, directly or indirectly, without the prior written consent of HILTD. This means that in the event you dispose of any device on which you have installed the Service, such as by sale or gift, you are responsible for deleting the Service from your mobile device prior to such disposition. HILTD may assign this Subscription Agreement, including all its rights hereunder, without restriction. Any assignment in violation of this Section is void.

          26. Survival. The provisions of this Subscription Agreement that are intended to survive the termination of this Subscription Agreement by their nature will survive the termination of this Subscription Agreement, including, but not limited to, Sections 2 (General), 3 (The Service), 5 (Fees and Payment Terms), 8 (Content You Submit; License Grants from You), 9 (Third Party Content), 10 (Use Restrictions), 11 (Security), 12 (Ownership), 13 (Feedback), 14 (Termination), 15 (Indemnity), 16 (No Warranty), 17 (Limitation of Liability), 18 (Third Party Disputes), 19 (Notice and Procedure for Making Claims of Copyright or Other Intellectual Property Infringements), 20 (Dispute Resolution), 21 (Arbitration Waiver), 22 (Governing Law), 23 (Recovery of Expenses), 24 (Jury Trial Waiver), 24 (Assignment), 25 (Survival), 27 (Consent to Electronic Communications) and 28 (Miscellaneous).

          27. Consent to Electronic Communications. By electronically signing this agreement, you affirmatively consent to receiving communications from us including but not limited to the service of all legal documents and court documents, through the email address provided to HILTD. You agree that any notices, agreements, disclosures, or other communications that we send to you electronically will satisfy any legal communication requirements, including that such communications be in writing, including the need to serve you personally with any summons and complaint for a lawsuit that may be filed in regard to your breach of Paragraph 10. BY SIGNING THIS AGREEMENT, YOU ARE HEREBY WAIVING ANY LEGAL RIGHT THAT YOU MAY HAVE TO CLAIM THAT PERSONAL SERVICE WAS INEFFECTIVE.

          28. Miscellaneous. The United Nations Convention on Contracts for the International Sale of Goods does not apply to this Subscription Agreement. This Subscription Agreement, together with the Privacy Policy and any other agreements expressly incorporated by reference herein, constitute the entire and exclusive understanding and agreement between you and HILTD regarding your use of and access to the Service, and, except as expressly permitted above, may be amended only by a written agreement signed by you and an authorized representative of = HILTD. The failure to require performance of any provision will not affect our right to require performance at any time thereafter, nor will a waiver of any breach or default of this Subscription Agreement or any provision of this Subscription Agreement constitute a waiver of any subsequent breach or default or a waiver of the provision itself. Use of section headers in this Subscription Agreement is for convenience only and will not have any impact on the interpretation of particular provisions. In the event that any part of this Subscription Agreement is held to be invalid or unenforceable, the unenforceable part will be given effect to the greatest extent possible and the remaining parts will remain in full force and effect. You agree that no joint venture, partnership, employment, or agency relationship exists between you and HILTD as a result of this Subscription Agreement or use of the Service. You acknowledge and agree that HILTD and HILTD's subsidiaries, and that HILTD will have the right to enforce this Subscription Agreement against you as a third-party beneficiary thereof. The English language version of this Subscription Agreement is the version that governs your use of the Service and in the event of any conflict between the English language version and a translated version, the English language version will control. You expressly agree that this Subscription Agreement and all ancillary documents be drafted solely in English.

          29. Contacting HILTD. If you have any comments, complaints, suggestions about this Subscription Agreement or the Service or otherwise would like to contact us, then you can contact HILTD by email at <a href="mailto:contactus@heyporn.com">contactus@heyporn.com</a>.

          Your access to this Website and access to and use of the Service is governed by and conditioned on your express consent to this Subscription Agreement. You have thoroughly reviewed this Subscription Agreement to your satisfaction. By clicking on the “JOIN” button, you agree to be bound by this Subscription Agreement, just as if you had signed it in pen and ink.
        </pre>
      </div>
    </MainPage>
  </div>
</template>

<script>
/*
  页面名称：协议页面
  创建人：许成祥
  创建时间：2020/04/11
  最近修改人：许成祥
  最近修改日期：2020/04/11
  备注： 无
*/
import MainPage from '../../components/MainPage'
export default {
  components: {
    MainPage
  },
  data () {
    return {
    }
  },
  computed: {
  },
  created () {
  },
  mounted () {
    this.$nextTick(() => {
    })
  },
  methods: {
  }
}
</script>

<style lang="scss" scoped>
@import 'page.scss';
</style>
